# Numpy Array Operation

In [1]:
import numpy as np

In [4]:
arr = np.arange(1, 10)
print("Basic Slicing", arr[3:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])


Basic Slicing [4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 7


In [5]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print("Specific element", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Entire column", arr_2d[:, 1])

Specific element 6
Entire row [4 5 6]
Entire column [2 5 8]


## Sorting

In [7]:
unsorted = np.array([3,4,5,6,6,7,83,2,4,5])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted =  np.array([[3,2],[4,5],[3,2]])
print("Sorted 2D array by column:\n", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [ 2  3  4  4  5  5  6  6  7 83]
Sorted 2D array by column:
 [[3 2]
 [3 2]
 [4 5]]


## Filter

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers", even_number)

Even Numbers [2 4 6 8]


## Filter with mask

In [9]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [6 7 8 9]


## Fancy indexing vs np.where()

In [10]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
NP where [6 7 8 9]


In [11]:
condition_array = np.where(numbers > 5 , "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


## Adding and removing data

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibilty

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,4])

print("Compatibilty shape", a.shape == b.shape)
print("Compatibilty shape", a.shape == c.shape)

Compatibilty shape True
Compatibilty shape False


In [19]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[2,3]])

with_new_row = np.vstack((original, new_row))
print(original)
print()
print(with_new_row)

new_col = np.array([[3], [4]])
with_new_col = np.hstack((original, new_col))
print("with new coloumn \n", with_new_col)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [2 3]]
with new coloumn 
 [[1 2 3]
 [3 4 4]]


In [20]:
arr = np.array([2,3,4,5,5,6])
deleted = np.delete(arr, 3)
print("Array after deletion : ", deleted)

Array after deletion :  [2 3 4 5 6]
