## Numpy array and basics
learn about numpy with chai aur code

In [2]:
import numpy as np


### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1,2,3]
print("Python list multiplication:", py_list * 2) 

np_array = np.array([1,2,3])# element wise multiplication
print("Python array multiplication:", np_array * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]

 List operation time:  0.07886266708374023

 Numpy operation time:  0.005439043045043945


### creating array from scrach

In [13]:
zeros = np.zeros((3,5))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.36896263 0.93386594 0.37882265]
 [0.67120393 0.59222966 0.14956957]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [18]:
vector = np.array([1,2,3])
print("vector: ", vector) 
 
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("matrix: \n", matrix) 

tensor = np.array([[[1,2], [2,3]],
                   [[5,6], [7,5]]])
print("Tensor: \n ", tensor)


vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
  [[[1 2]
  [2 3]]

 [[5 6]
  [7 5]]]
